# Numpy: um introdução

[Numpy](https://numpy.org/) é, senão a mais, uma das mais populares bibliotecas para computação numérica na comunidade do Python. De tal forma que muitas outras bibliotecas desse segmento, quando não impletam suas funcionalidades usando o próprio Numpy como base, garantem com aquela um certo grau de compatibilidade ou suporte.  
A biblioteca implementa uma extrutura de dados (a [ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html#the-n-dimensional-array-ndarray)) homogênea (os dados são do mesmo tipo), cujos elementos podem ser acessados por índices inteiros. Comparadas as estruturas como listas e tuplas padrões do Python, a ndarray oferce vantagens para computação numérica, otimizando recursos como memória e poder de processamento. Ela também apresenta um recuso chamado "[vetorização](https://numpy.org/doc/stable/glossary.html#term-vectorization)" (_vecotirzation_), que permite realizar operações com cada elemento do arranjo, de forma simples, reduzindo a necessidade do uso de _loops_ (_for_, _while_).
Para entender melhor, vamos a algumas práticas com a biblioteca, començando pela tradicional importação dos módulos e escrita de algumas rotinas básicas.

In [1]:
import numpy as np # Importação do Numpy. "as np" cria um "alias" (apelido) para "numpy"

In [6]:
x = np.array([1, 2, 3])
y = np.arange(0, 2, .5)
z = np.linspace(0, 10, 6)

In [7]:
x, y, z

(array([1, 2, 3]),
 array([0. , 0.5, 1. , 1.5]),
 array([ 0.,  2.,  4.,  6.,  8., 10.]))

Os métodos **array**, **arange** e **linspace** retornam arranjos (arrays) numéricos, seguido diferentes processos de criação.  
- [_array_](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) retorna um obeto array numpy, contando os valores passados na lista.
- [_arange_](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) retornar um arranjo contendo valores no intervalo definido pelo primeito e último parâmetro, com espaçamento dado pelo terceiro parâmetro.
- [_linspace_](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) funciona quase como _arange_, mas o terceiro parâmetro expressa a quantidade de elementos do intervalo, em vez do espaçamento.

In [14]:
mat = np.array([[1., .2, 5], [0, -3, -1], [.2, np.pi, 0]])

In [15]:
mat

array([[ 1.        ,  0.2       ,  5.        ],
       [ 0.        , -3.        , -1.        ],
       [ 0.2       ,  3.14159265,  0.        ]])

In [16]:
np.linalg.det(mat)

6.101592653589793

Acima, em sequência, declaramos uma matriz quadrada (mat), imprimimos em tela e calculamos seu determinante, usado a função [det](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det) do pacote [linalg](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg).

**Continua... WDG - 2024/01/19**